services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onandoff
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: back/api/main
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8042
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      AI_URL: http://ai:5042
      FRONTEND_URL: http://localhost:3042
      JWT_SECRET: xi4EowgBJUe7NAcKAYAHxeHstOyAxtaU0p3XcSR4o0k=
      JWT_EXPIRATION: 86400000
    ports:
      - "8042:8042"
    depends_on:
      - db
    volumes:
      - ./back/api/main/uploads:/app/uploads

  ai:
    build: back/ai/main
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      API_URL: http://api:8042
      SERVER_PORT: 5042
    ports:
      - "5042:5042"
    depends_on:
      - api

  front:
    build:
      context: front/main
      args:
        REACT_APP_API_URL: http://localhost:8042
        REACT_APP_AI_URL: http://localhost:5042
    ports:
      - "3042:80"
    depends_on:
      - api
      - ai

volumes:
  mysql-data:
